// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkGya0lHqshvVDkwZwDl52C8u1lNPAWLE',
    appId: '1:23913846527:web:114c3beab1dd745530deca',
    messagingSenderId: '23913846527',
    projectId: 'flutter-musobaqasi',
    authDomain: 'flutter-musobaqasi.firebaseapp.com',
    storageBucket: 'flutter-musobaqasi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe9tOiAi5UOq81KCZ-6rd0d2-ADAqZu24',
    appId: '1:23913846527:android:b6dc0695b759352e30deca',
    messagingSenderId: '23913846527',
    projectId: 'flutter-musobaqasi',
    storageBucket: 'flutter-musobaqasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvHcPus_G46ch6zMc5He_ugIvO_d-mrI',
    appId: '1:23913846527:ios:7f3f2c52e97d31e030deca',
    messagingSenderId: '23913846527',
    projectId: 'flutter-musobaqasi',
    storageBucket: 'flutter-musobaqasi.appspot.com',
    iosBundleId: 'com.example.musobaqa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvHcPus_G46ch6zMc5He_ugIvO_d-mrI',
    appId: '1:23913846527:ios:7f3f2c52e97d31e030deca',
    messagingSenderId: '23913846527',
    projectId: 'flutter-musobaqasi',
    storageBucket: 'flutter-musobaqasi.appspot.com',
    iosBundleId: 'com.example.musobaqa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkGya0lHqshvVDkwZwDl52C8u1lNPAWLE',
    appId: '1:23913846527:web:31a6733350e9c11830deca',
    messagingSenderId: '23913846527',
    projectId: 'flutter-musobaqasi',
    authDomain: 'flutter-musobaqasi.firebaseapp.com',
    storageBucket: 'flutter-musobaqasi.appspot.com',
  );
}
